---
- name: Install editors
  pacman:
    name: "{{ editors }}"
    state: present

- name: Install Pip NeoVim Plugin
  pip:
      name: neovim
  when: '"neovim" in editors'

- name: Install NeoVim Plugins
  shell: nvim +'PlugInstall --sync' +qa
  when: '"neovim" in editors'
