---
- name: Install mpv
  pacman: name=mpv state=present

- name: Jail mpv
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/mpv
        state=link
  tags:
    - firejail

- name: Add SMPlayer
  pacman: name=smplayer state=present