---
- name: Install stow
  pacman: name=stow state=present
  when: dotfiles is defined

- name: Clone user dotfiles
  git: repo={{ dotfiles.url }} dest=/home/{{ user.name }}/{{ dotfiles.destination }} accept_hostkey=yes update=no
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"

- name: Install user dotfiles
  command: stow "{{ item }}"
  with_fileglob:
    - /home/{{ user.name }}/{{ dotfiles.destination }}/*
  when: dotfiles is defined
  become: yes
  become_user: "{{ user.name }}"
  args:
    chdir: /home/{{ user.name }}/{{ dotfiles.destination }}