---
- include_tasks: "arch.yml"
  when: ansible_os_family == "Archlinux"

- include: user.yml
- include: shell.yml
- include: sudo.yml
- include: arch_packages.yml
  when: ansible_os_family == "Archlinux"
- include: journal.yml