---
- name: Install LightDM
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
    state: present

- name: Enable LightDM
  service: name=lightdm.service enabled=yes

- name: Create background dir
  file: path=/usr/share/pixmaps state=directory

- name: Push LightDM greeter background
  copy: src=wallpaper.jpg dest=/usr/share/pixmaps/dm-background.jpg

- name: Push LightDM greeter user image
  copy: src=lightdm-gtk-greeter.conf dest=/usr/share/pixmaps/dm-user.png

- name: Push LightDM greeter conf
  copy: src=user.png dest=/etc/lightdm/lightdm-gtk-greeter.conf

- name: Force LightDM greeter theme
  lineinfile: dest=/usr/share/xgreeters/lightdm-gtk-greeter.desktop
              regexp="^Exec="
              state=present
              line="Exec=env GTK_THEME=Adwaita:dark lightdm-gtk-greeter"