---
- hosts: localhost
  become: yes
  roles:
    - { role: base, tags: ['base'] }
    - { role: grub, tags: ['grub'] }
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    - { role: ssh, tags: ['ssh'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: editors, tags: ['editors'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: x, tags: ['x'] }
    - { role: lightdm, tags: ['lightdm'], when: "display_manager == 'lightdm'" }
    - { role: i3, tags: ['i3'], when: "desktop_environment == 'i3'" }
    - { role: nettools, tags: ['nettools'] }
    - { role: networkmanager, tags: ['networkmanager'] }
    - { role: firejail, tags: ['firejail'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: pass, tags: ['pass'] }
    - { role: sound, tags: ['sound'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: bluetooth, tags: ['bluetooth'], when: "bluetooth is defined" }
    - { role: taskwarrior, tags: ['taskwarrior'] }
    - { role: golang, tags: ['golang'] }
    - { role: php, tags: ['php'] }
    - { role: office, tags: ['office'] }
    - { role: pdf, tags: ['pdf'] }
    - { role: calibre, tags: ['calibre'] }
    - { role: media, tags: ['media'] }
    - { role: themes, tags: ['themes'] }
    - { role: mpd, tags: ['mpd'] }
    - { role: mpv, tags: ['mpv'] }
    - { role: docker, tags: ['docker'] }
    - { role: mail, tags: ['mail'] }
  vars_prompt:
      - name: user_password
        prompt: "Enter desired user password"
